language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"

before_deploy:
  script: meteor build .

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "spbstu-admission.tar.gz"
  skip_cleanup: true
  on:
    tags: true